### PR TITLE
Fix broken Authconfig in Python 3.x

### PR DESCRIPTION
**Pull request by stdevel**

### CODE REVIEW

**Comment by stdevel** [comment]
The patches applied already help with encypting the files, but reading/decrypting doesn't work, yet.

**Comment by okin** [comment]
@stdevel  I fixed the container to work with Python 3. There is no backwards compat the Py 2.

Tested the CLI and it did work for me.

**Comment by okin** [comment]
@stdevel wouldn't it be more benefical right now if the changes land in the branch for Uyuni support (`43-...`)?

**Comment by stdevel** [comment]
> @stdevel wouldn't it be more benefical right now if the changes land in the branch for Uyuni support (`43-...`)?

Good idea - just changed the base.

Thanks for your work - is your PR considered ready now?

**Comment by okin** [comment]
> Thanks for your work - is your PR considered ready now?

Yes - worked in all my tests.

**Pull request merged**
